cricket_analytics:
  target: dev
  outputs:

    dev:
      type: duckdb
      path: "../data/gold.duckdb"
      threads: 4

    prod:
      type: duckdb
      path: "../data/gold.duckdb"
      threads: 4
      extensions:
        - azure
      secrets:
        - type: azure
          account_name: cricketanalyticsdata
          account_key: "{{ env_var('AZURE_STORAGE_ACCOUNT_KEY') }}"
